import net from 'node:net';
import http from 'node:http';
import {URL} from 'node:url';
import WebSocket from 'ws';

const CKM_BASE=String(process.env.CKM_BASE_URL||'').replace(/\/$/,'');
const CKM_SECRET=String(process.env.CKM_PHONE_GATEWAY_SECRET||'');
const DEEPGRAM_KEY=String(process.env.DEEPGRAM_API_KEY||'');
const HTTP_HOST=String(process.env.CKM_PHONE_HTTP_HOST||'127.0.0.1');
const HTTP_PORT=Number(process.env.CKM_PHONE_HTTP_PORT||9018);
const AUDIO_HOST=String(process.env.CKM_AUDIOSOCKET_HOST||'0.0.0.0');
const AUDIO_PORT=Number(process.env.CKM_AUDIOSOCKET_PORT||9019);
const CONTROL_URL=String(process.env.ASTERISK_CONTROL_URL||'');
if(!CKM_BASE||!CKM_SECRET||!DEEPGRAM_KEY)throw new Error('Set CKM_BASE_URL, CKM_PHONE_GATEWAY_SECRET and DEEPGRAM_API_KEY.');
const calls=new Map(), pending=new Map();
const api=p=>`${CKM_BASE}/wp-json/ckm/v1/sales/phone-gateway/${p}`;
async function post(path,body={}){const r=await fetch(api(path),{method:'POST',headers:{'content-type':'application/json','x-ckm-phone-gateway-secret':CKM_SECRET},body:JSON.stringify(body)});const t=await r.text();let d={};try{d=t?JSON.parse(t):{};}catch{d={raw:t};}if(!r.ok||d.ok===false)throw new Error(d.message||`CKM ${path} HTTP ${r.status}`);return d;}
function frame(type,payload=Buffer.alloc(0)){const h=Buffer.alloc(3);h[0]=type;h.writeUInt16BE(payload.length,1);return Buffer.concat([h,payload]);}
function parseWav(buf){if(buf.length<44||buf.toString('ascii',0,4)!=='RIFF'||buf.toString('ascii',8,12)!=='WAVE')throw new Error('Sergey Gateway returned non-WAV audio');let o=12,fmt=null,data=null;while(o+8<=buf.length){const id=buf.toString('ascii',o,o+4),len=buf.readUInt32LE(o+4),p=o+8;if(id==='fmt ')fmt={format:buf.readUInt16LE(p),channels:buf.readUInt16LE(p+2),rate:buf.readUInt32LE(p+4),bits:buf.readUInt16LE(p+14)};if(id==='data'){data=buf.subarray(p,p+len);break;}o=p+len+(len%2);}if(!fmt||!data||fmt.format!==1||fmt.bits!==16)throw new Error('Sergey WAV must be PCM16');return {fmt,data};}
function mono8k(wav){const {fmt,data}=parseWav(wav),frames=Math.floor(data.length/(2*fmt.channels)),outFrames=Math.max(1,Math.floor(frames*8000/fmt.rate)),out=Buffer.alloc(outFrames*2);for(let i=0;i<outFrames;i++){const src=Math.min(frames-1,Math.floor(i*fmt.rate/8000));let sum=0;for(let c=0;c<fmt.channels;c++)sum+=data.readInt16LE((src*fmt.channels+c)*2);out.writeInt16LE(Math.max(-32768,Math.min(32767,Math.round(sum/fmt.channels))),i*2);}return out;}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function sendPcm(call,pcm,generation){for(let o=0;o<pcm.length;o+=320){if(call.playGeneration!==generation||call.closed)return;const chunk=pcm.subarray(o,Math.min(o+320,pcm.length));call.socket.write(frame(0x10,chunk));await sleep(20);}}
async function voice(call,ticket,turnIndex){if(!ticket?.ready||!ticket.wsUrl||!ticket.ttsToken)throw new Error('CKM Sergey voice ticket unavailable');const gen=++call.playGeneration;const ws=new WebSocket(ticket.wsUrl);let joined=false,collect=false,parts=[];await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Sergey Gateway join timeout')),8000);ws.on('open',()=>ws.send(JSON.stringify({type:'join',game_id:String(ticket.gameId),role:'scoreboard',token:String(ticket.ttsToken)})));ws.on('message',async (raw,isBinary)=>{if(!isBinary){const text=typeof raw==='string'?raw:raw.toString();let m;try{m=JSON.parse(text);}catch{return;}if(m.type==='joined'&&!joined){joined=true;try{await post('speak',{call_uuid:call.uuid,turn_index:turnIndex});}catch(e){clearTimeout(timer);reject(e);ws.close();}}else if(m.type==='voice_start'){collect=true;parts=[];}else if(m.type==='voice_end'&&collect){collect=false;clearTimeout(timer);try{const pcm=mono8k(Buffer.concat(parts));await sendPcm(call,pcm,gen);resolve();}catch(e){reject(e);}finally{ws.close();}}else if(m.type==='voice_failed'){clearTimeout(timer);reject(new Error(m.detail||m.error||'Sergey voice_failed'));ws.close();}return;}if(collect)parts.push(Buffer.from(raw));});ws.on('error',e=>{clearTimeout(timer);reject(e);});ws.on('close',()=>{if(!joined)reject(new Error('Sergey Gateway closed before join'));});});}
async function processUtterance(call,text){text=String(text||'').trim();if(!text||call.busy||call.closed)return;call.busy=true;try{const r=await post('turn',{call_uuid:call.uuid,text});if(r.queued_for_operator)return;if(r.reply&&Number.isInteger(r.turn_index))await voice(call,r.voice_ticket,r.turn_index);if(r.intent==='end'){await post('event',{call_uuid:call.uuid,status:'completed'}).catch(()=>{});call.socket.end();}}catch(e){console.error('turn',call.uuid,e.message);await post('event',{call_uuid:call.uuid,status:'failed',detail:e.message}).catch(()=>{});}finally{call.busy=false;}}
function deepgram(call){const qs=new URLSearchParams({model:'nova-3',language:'ru',encoding:'linear16',sample_rate:'8000',channels:'1',punctuate:'true',interim_results:'true',endpointing:'350'});const ws=new WebSocket(`wss://api.deepgram.com/v1/listen?${qs}`,{headers:{Authorization:`Token ${DEEPGRAM_KEY}`}});call.dg=ws;let finals=[];ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString());}catch{return;}if(m.type==='SpeechStarted'){call.playGeneration++;return;}if(m.type!=='Results')return;const t=String(m.channel?.alternatives?.[0]?.transcript||'').trim();if(m.is_final&&t)finals.push(t);if(m.speech_final){const whole=finals.join(' ').trim();finals=[];if(whole)processUtterance(call,whole);}});ws.on('error',e=>console.error('deepgram',call.uuid,e.message));return ws;}
function parseFrames(state,chunk,onFrame){state.buf=Buffer.concat([state.buf,chunk]);while(state.buf.length>=3){const type=state.buf[0],len=state.buf.readUInt16BE(1);if(state.buf.length<3+len)return;const p=state.buf.subarray(3,3+len);state.buf=state.buf.subarray(3+len);onFrame(type,p);}}
async function commands(call){if(call.closed)return;try{const r=await post('commands',{call_uuid:call.uuid});for(const c of (r.commands||[])){if(c.type==='hangup'){call.closed=true;call.socket.end();await post('event',{call_uuid:call.uuid,status:'hangup'}).catch(()=>{});}else if(c.type==='transfer'){if(!CONTROL_URL){await post('event',{call_uuid:call.uuid,status:'transfer_failed',detail:'ASTERISK_CONTROL_URL is not configured'}).catch(()=>{});continue;}const x=await fetch(CONTROL_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'transfer',call_uuid:call.uuid,target_uri:c.target_uri})});if(!x.ok)throw new Error(`Asterisk control HTTP ${x.status}`);await post('event',{call_uuid:call.uuid,status:'transferred'}).catch(()=>{});call.closed=true;call.socket.end();}}}catch(e){console.error('commands',call.uuid,e.message);}if(!call.closed)setTimeout(()=>commands(call),1000);}
function attach(socket){const state={buf:Buffer.alloc(0)},call={socket,uuid:'',dg:null,busy:false,closed:false,playGeneration:0};socket.on('data',chunk=>parseFrames(state,chunk,(type,p)=>{if(type===0x01&&p.length===16&&!call.uuid){const h=p.toString('hex');call.uuid=`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;calls.set(call.uuid,call);const meta=pending.get(call.uuid);if(!meta){socket.destroy(new Error('Call was not initialized over local HTTP'));return;}pending.delete(call.uuid);call.dg=deepgram(call);commands(call);post('event',{call_uuid:call.uuid,status:'connected'}).catch(()=>{});}else if(type>=0x10&&type<=0x18&&call.dg?.readyState===WebSocket.OPEN){call.dg.send(p);}else if(type===0x00){call.closed=true;socket.end();}}));socket.on('close',()=>{call.closed=true;if(call.dg?.readyState===WebSocket.OPEN)call.dg.close();if(call.uuid){calls.delete(call.uuid);post('event',{call_uuid:call.uuid,status:'completed'}).catch(()=>{});}});socket.on('error',e=>console.error('audiosocket',call.uuid||'pending',e.message));}
net.createServer(attach).listen(AUDIO_PORT,AUDIO_HOST,()=>console.log(`AudioSocket ${AUDIO_HOST}:${AUDIO_PORT}`));
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/health'){res.setHeader('content-type','application/json');res.end(JSON.stringify({ok:true,service:'ckm-phone-media-gateway',active_calls:calls.size,deepgram_ready:true,audiosocket_ready:true}));return;}if(u.pathname==='/calls/inbound'){const uuid=String(u.searchParams.get('uuid')||'').toLowerCase(),did=String(u.searchParams.get('did')||''),caller=String(u.searchParams.get('caller')||'');const r=await post('open',{call_uuid:uuid,did,caller});pending.set(uuid,r);res.setHeader('content-type','application/json');res.end(JSON.stringify({ok:true,call_uuid:uuid,voice:'Сергей'}));return;}res.statusCode=404;res.end('not found');}catch(e){res.statusCode=422;res.setHeader('content-type','application/json');res.end(JSON.stringify({ok:false,error:e.message}));}}).listen(HTTP_PORT,HTTP_HOST,()=>console.log(`Local control http://${HTTP_HOST}:${HTTP_PORT}`));
setInterval(()=>post('heartbeat',{service:'ckm-phone-media-gateway',version:'531',deepgram_ready:true,audiosocket_ready:true,active_calls:calls.size}).catch(e=>console.error('heartbeat',e.message)),15000);
await post('heartbeat',{service:'ckm-phone-media-gateway',version:'531',deepgram_ready:true,audiosocket_ready:true,active_calls:0});
