<?php
require_once __DIR__ . '/support/plugin-release.php';
$root=dirname(__DIR__);
$checks=[];
function b332(&$c,$ok,$name){$c[]=[$ok,$name];echo($ok?'PASS ':'FAIL ').$name."\n";}
$plugin=file_get_contents($root.'/ckm-quiz-pro.php');
$boot=file_get_contents($root.'/modules/negotiation-master/bootstrap.php');
$schema=json_decode(file_get_contents($root.'/modules/negotiation-master/schema.json'),true);
$repo=file_get_contents($root.'/modules/negotiation-master/repositories.php');
$sec=file_get_contents($root.'/modules/negotiation-master/security.php');
$svc=file_get_contents($root.'/modules/negotiation-master/application/scenario-builder-service.php');
$api=file_get_contents($root.'/modules/negotiation-master/api/builder-controller.php');
$page=file_get_contents($root.'/modules/negotiation-master/public/builder-page.php');
$player=file_get_contents($root.'/modules/negotiation-master/public/player-page.php');
$catalog=file_get_contents($root.'/modules/negotiation-master/public/product-catalog.php');
$js=file_get_contents($root.'/modules/negotiation-master/assets/negotiation-builder.js');
$snap=file_get_contents($root.'/modules/negotiation-master/application/player-session-snapshot-builder.php');
b332($checks,ckm_test_current_plugin_release($plugin),'plugin build');
b332($checks,preg_match("/CKM_NEG_DB_VERSION', '([0-9.]+)'/",$boot,$dbPin)&&version_compare($dbPin[1],'1.8.0','>=')&&preg_match("/CKM_NEG_CONTENT_VERSION', '([0-9.]+)'/",$boot,$contentPin)&&str_contains(file_get_contents($root.'/modules/negotiation-master/content/system-v1.php'),'"pack_version": "'.$contentPin[1].'"'),'schema supports builder QA and current seed pin matches bootstrap');
b332($checks,isset($schema['sessions']['columns']['session_kind'])&&str_contains($schema['sessions']['columns']['session_kind'],"DEFAULT 'player'"),'session_kind schema default');
b332($checks,isset($schema['sessions']['indexes']['session_kind']),'session_kind indexed');
b332($checks,str_contains($repo,"'session_kind' => 'player'")&&str_contains($repo,"'session_kind' => 'builder_test'"),'runtime distinguishes player and builder test sessions');
b332($checks,str_contains($repo,"session_kind='player' AND status IN ('in_progress','paused')"),'normal active session query excludes tests');
b332($checks,str_contains($repo,'createBuilderTestRuntime')&&str_contains($repo,'abandonBuilderTestsForScenario'),'builder test repository lifecycle');
b332($checks,str_contains($sec,'canUseBuilderForOwnDraft')&&str_contains($sec,"row['status'] === 'draft'"),'own draft access is builder-scoped');
b332($checks,str_contains($svc,'public function testLaunch')&&str_contains($svc,'validateDetail($detail, true)'),'test launch uses publish-grade validation');
b332($checks,str_contains($svc,'createBuilderTestRuntime')&&str_contains($svc,"ProductCatalog::url(['neg_test_session'=>\$sessionId])"),'test launch returns isolated player URL');
b332($checks,str_contains($api,'/test-launch')&&str_contains($api,'public static function testLaunch'),'builder REST test route');
b332($checks,str_contains($page,'ckm-neg-builder-test')&&str_contains($page,'Тестировать черновик'),'test button in builder UI');
b332($checks,str_contains($js,'scheduleAutosave')&&str_contains($js,'1400'),'debounced autosave');
b332($checks,str_contains($js,"save({silent:true})")&&str_contains($js,'beforeunload'),'autosave and dirty-leave warning');
b332($checks,str_contains($js,"'/test-launch'")&&str_contains($js,"window.open('about:blank'"),'draft test launch opens from editor');
b332($checks,str_contains($page,'openScenarioId')&&str_contains($js,'C.openScenarioId'),'return path can reopen edited scenario');
b332($checks,str_contains($player,'neg_test_session')&&str_contains($player,"session_kind'] ?? 'player') !== 'builder_test'"),'player page recognizes only builder_test direct session');
b332($checks,str_contains($player,"'builderTest' => \$isBuilderTest")&&str_contains($player,'Тест черновика'),'test-run is visibly marked');
b332($checks,str_contains($snap,"'session_kind'")&&str_contains($snap,"'builder_test'"),'snapshot exposes safe test marker');
b332($checks,substr_count($catalog,"session_kind='player'")>=5,'catalog/history/progress exclude builder tests');
b332($checks,str_contains($catalog,"if ((\$row['session_kind'] ?? 'player') !== 'player') { return null; }"),'normal requested session cannot open builder test');
b332($checks,str_contains($svc,"session_kind='player'"),'archive history guard ignores test-only runs');
$failed=array_filter($checks,fn($x)=>!$x[0]);
echo count($checks).' checks, '.count($failed)." failed\n";
exit($failed?1:0);
