<?php
require_once __DIR__ . '/support/plugin-release.php';
$root=dirname(__DIR__);$checks=[];
function a333(&$c,$ok,$name){$c[]=[$ok,$name];echo($ok?'PASS ':'FAIL ').$name."\n";}
$plugin=file_get_contents($root.'/ckm-quiz-pro.php');
$boot=file_get_contents($root.'/modules/negotiation-master/bootstrap.php');
$schema=json_decode(file_get_contents($root.'/modules/negotiation-master/schema.json'),true);
$sec=file_get_contents($root.'/modules/negotiation-master/security.php');
$repo=file_get_contents($root.'/modules/negotiation-master/repositories.php');
$svc=file_get_contents($root.'/modules/negotiation-master/application/assignment-service.php');
$api=file_get_contents($root.'/modules/negotiation-master/api/assignment-controller.php');
$page=file_get_contents($root.'/modules/negotiation-master/public/assignment-page.php');
$player=file_get_contents($root.'/modules/negotiation-master/public/player-page.php');
$snap=file_get_contents($root.'/modules/negotiation-master/application/player-session-snapshot-builder.php');
$sessionApi=file_get_contents($root.'/modules/negotiation-master/api/session-controller.php');
$sessionSvc=file_get_contents($root.'/modules/negotiation-master/application/session-service.php');
$js=file_get_contents($root.'/modules/negotiation-master/assets/negotiation-assignments.js');
$gamejs=file_get_contents($root.'/modules/negotiation-master/assets/negotiation-session.js');
a333($checks,ckm_test_current_plugin_release($plugin),'plugin build');
a333($checks,preg_match("/CKM_NEG_DB_VERSION', '([0-9.]+)'/",$boot,$dbPin)&&version_compare($dbPin[1],'1.7.0','>=')&&preg_match("/CKM_NEG_CONTENT_VERSION', '([0-9.]+)'/",$boot,$contentPin)&&str_contains(file_get_contents($root.'/modules/negotiation-master/content/system-v1.php'),'"pack_version": "'.$contentPin[1].'"'),'schema supports assignments and current seed pin matches bootstrap');
a333($checks,count($schema)===17&&isset($schema['assignments'],$schema['assignment_participants']),'17 NEG tables including assignments');
a333($checks,isset($schema['assignments']['columns']['scenario_version_id'],$schema['assignments']['columns']['deadline_at'],$schema['assignments']['columns']['result_visibility']),'assignment pin/deadline/result schema');
a333($checks,isset($schema['assignment_participants']['unique']['assignment_user'])&&isset($schema['assignment_participants']['indexes']['assignment_team']),'participant uniqueness and team index');
a333($checks,str_contains($boot,'assignment-service.php')&&str_contains($boot,'assignment-controller.php')&&str_contains($boot,'assignment-page.php'),'assignment module bootstrapped');
a333($checks,str_contains($boot,"[AssignmentController::class, 'register']")&&str_contains($boot,"[AssignmentPage::class, 'install']"),'assignment API/page hooks');
a333($checks,str_contains($svc,'public function create(')&&str_contains($svc,'scenario_version_id')&&str_contains($svc,"'status'=>'draft'"),'assignment creation pins current published version');
a333($checks,str_contains($svc,"['individual','team_shared']")&&str_contains($svc,"assignment-team:"),'individual and shared-team modes');
a333($checks,str_contains($svc,"['training','exam']")&&str_contains($svc,'max_attempts'),'mode and attempt limit');
a333($checks,str_contains($svc,"['immediate','after_deadline','organizer_only']"),'result visibility policies');
a333($checks,str_contains($svc,'parseDeadline')&&str_contains($svc,'Срок выполнения назначения истёк'),'deadline validation/enforcement');
a333($checks,str_contains($svc,'resolveUser')&&str_contains($svc,"get_user_by('email'")&&str_contains($svc,"get_user_by('login'"),'existing account assignment by id/email/login');
a333($checks,str_contains($svc,'addParticipants')&&str_contains($svc,'removeParticipant'),'participant management');
a333($checks,str_contains($svc,'setStatus(int $assignmentId, string $status)')&&str_contains($svc,"['active','closed']"),'assignment activation/closure');
a333($checks,str_contains($svc,'public function mine()')&&str_contains($svc,'participantReport'),'participant dashboard and organizer progress report');
a333($checks,str_contains($svc,'public function launch(')&&str_contains($svc,'countCompletedForAssignment')&&str_contains($svc,'createAssignedRuntime'),'launch enforces attempt limit and creates assignment runtime');
a333($checks,str_contains($repo,'findActiveForAssignment')&&str_contains($repo,'countCompletedForAssignment')&&str_contains($repo,"'session_kind'=>'assignment'"),'session repository assignment lifecycle');
a333($checks,str_contains($sec,'assignedParticipantForTenant')&&str_contains($sec,'assignedSessionAllowed'),'assigned participant tenant/session access');
a333($checks,str_contains($sec,'assignment-team:')&&str_contains($sec,"session_kind'] ?? '') !== 'assignment'"),'team members share only assignment team session');
a333($checks,str_contains($api,'/negotiation/assignments/mine')&&str_contains($api,"/launch'")&&str_contains($api,"/activate'")&&str_contains($api,"/close'"),'assignment REST routes');
a333($checks,str_contains($page,'ckm-negotiation-assignments')&&str_contains($page,'Назначения')&&str_contains($page,'Общая сессия команды'),'frontend assignment page');
a333($checks,str_contains($js,"'/assignments/mine'")&&str_contains($js,"'/launch'")&&str_contains($js,'Копировать ссылку'),'participant launch and share UI');
a333($checks,str_contains($player,'neg_assignment_session')&&str_contains($player,'Назначенная игра'),'player page recognizes assignment session');
a333($checks,str_contains($player,'$isAssignmentSession ? AssignmentPage::url'),'assignment return route');
a333($checks,str_contains($snap,"'assignment' =>")&&str_contains($snap,'assignment_blocked_message'),'safe snapshot marks assignment and blocking state');
a333($checks,str_contains($sessionSvc,"session_kind'] ?? 'player') === 'assignment'")&&str_contains($sessionSvc,'assertSessionWritable'),'resume respects assignment deadline/status');
a333($checks,str_contains($sessionApi,'resultVisibleForSession')&&substr_count($sessionApi,'assertSessionWritable')>=2,'session writes/results enforce assignment policy');
a333($checks,str_contains($gamejs,'renderEvaluationHidden')&&str_contains($gamejs,'r.hidden'),'hidden participant result UI');
a333($checks,str_contains($svc,'LibraryAccessService')&&str_contains($svc,'assertScenarioAccess'),'organizer assignment respects existing library access');
$failed=array_filter($checks,fn($x)=>!$x[0]);
echo count($checks).' checks, '.count($failed)." failed\n";exit($failed?1:0);
