<?php
require_once __DIR__ . '/support/plugin-release.php';
$root=dirname(__DIR__);
$main=file_get_contents($root.'/ckm-quiz-pro.php');
$schema=file_get_contents($root.'/includes/partner/schema.php');
$loader=file_get_contents($root.'/includes/partner/loader.php');
$checkout=file_get_contents($root.'/includes/partner/plan-checkout.php');
$front=file_get_contents($root.'/includes/partner/frontend.php');
$admin=file_get_contents($root.'/includes/partner/admin.php');
$access=file_get_contents($root.'/includes/partner/access.php');
$c=[];
function pc277(&$c,$ok,$name){$c[]=$ok;echo ($ok?'PASS':'FAIL')." $name\n";}
pc277($c,ckm_test_current_plugin_release($main),'version marker');
pc277($c,str_contains($schema,"'plan_orders'") && str_contains($schema,'last_payment_ref varchar(96)'),'plan order schema and subscription payment ref');
pc277($c,str_contains($schema,'session_limit int unsigned') && str_contains($schema,'activated_at datetime'),'order snapshots limit and activation');
pc277($c,str_contains($loader,"require_once __DIR__ . '/plan-checkout.php'"),'checkout module loaded');
pc277($c,str_contains($loader,'ckm_quiz_pro_partner_plan_register_routes'),'platform webhook route registered');
pc277($c,str_contains($checkout,"aes-256-gcm") && str_contains($checkout,"ckm-platform-yookassa-v1"),'platform Secret key encrypted separately');
pc277($c,str_contains($checkout,'https://api.yookassa.ru/v3/') && str_contains($checkout,"'Authorization' => 'Basic '"),'central YooKassa server API');
pc277($c,str_contains($checkout,"'Idempotence-Key'") && str_contains($checkout,"'ckm-plan-'"),'stable idempotence key');
pc277($c,str_contains($checkout,"'GET', 'me'") && str_contains($checkout,'mode_mismatch'),'shop and test/live verification');
pc277($c,str_contains($checkout,"'receipt'") && str_contains($checkout,"'payment_subject'=>'service'"),'54-FZ receipt service item');
pc277($c,str_contains($checkout,"'ckm_type'=>'partner_plan'") && str_contains($checkout,"'tenant_id'") && str_contains($checkout,"'plan_key'"),'payment metadata scoped to order tenant plan');
pc277($c,str_contains($checkout,'Never activate from webhook payload alone') && str_contains($checkout,"'GET', 'payments/'"),'webhook re-fetches payment');
pc277($c,str_contains($checkout,"recipient") && str_contains($checkout,"amount_minor") && str_contains($checkout,"metadata"),'reconcile validates recipient amount metadata');
pc277($c,str_contains($checkout,"mode_missing") && str_contains($checkout,"authoritative API"),'plan reconcile rejects missing merchant/mode fields');
pc277($c,str_contains($checkout,'SELECT GET_LOCK') && str_contains($checkout,'SELECT RELEASE_LOCK'),'concurrent webhook guard');
pc277($c,str_contains($access,'string $paymentRef =') && str_contains($access,"'last_payment_ref'"),'activation idempotent by payment reference');
pc277($c,str_contains($checkout,'ckm_quiz_pro_partner_activate') && str_contains($checkout,"'activated_at'"),'successful payment auto-activates partner plan');
pc277($c,str_contains($front,"plan_payment_return") && str_contains($front,'Оплата подтверждена. Партнёрский режим активирован автоматически'),'return path syncs activation');
pc277($c,str_contains($front,'ckm_quiz_pro_partner_plan_start_checkout') && str_contains($front,'wp_redirect($payUrl'),'plan selection starts YooKassa checkout');
pc277($c,str_contains($front,"partner_action\" value=\"renew_plan") && str_contains($front,'Продлить '),'active plan can renew through YooKassa');
pc277($c,str_contains($admin,'save_platform_yookassa') && str_contains($admin,'test_platform_yookassa'),'admin can configure and test central YooKassa');
pc277($c,str_contains($admin,'Сохранить тарифы и лимиты'),'admin save label covers prices and limits');
pc277($c,str_contains($checkout,'Webhook YooKassa:') && str_contains($checkout,'payment.succeeded'),'admin receives webhook URL/instructions');
pc277($c,str_contains($checkout,'Последние оплаты партнёрского режима'),'admin payment audit table');
pc277($c,!str_contains($checkout,'ckm_quiz_pro_partner_yk_api($tenantId'),'central plan checkout does not use tenant partner cash desk');
$fail=count(array_filter($c,fn($x)=>!$x));
echo 'TOTAL '.count($c).' FAIL '.$fail."\n";
exit($fail?1:0);
