<?php
namespace CKM\EffectiveSales;
if (!defined('ABSPATH')) { exit; }

/**
 * Platform-owned GPT-Live Direct SIP control plane.
 * Partner SIP credentials remain tenant-scoped; the platform AI key is global and admin-only.
 * Audio is exchanged directly between the SIP provider and OpenAI, never proxied through WordPress.
 */
final class SalesLiveSipService {
    private const OPTION='ckm_sales_live_sip_platform_v1';
    private const CALLS_OPTION='ckm_sales_live_sip_calls_v1';
    private const API_BASE='https://api.openai.com/v1';
    private const MODEL='gpt-live-1';
    private const WEBHOOK_TOLERANCE=300;
    private $transport;
    public function __construct(?callable $transport=null){$this->transport=$transport;}

    private static function clean(string $v,int $max=500): string {$v=trim(wp_strip_all_tags($v));return function_exists('mb_substr')?mb_substr($v,0,$max,'UTF-8'):substr($v,0,$max);}
    private static function requireAdmin(): void {if(!current_user_can('manage_options'))throw new \RuntimeException('Голосовую инфраструктуру платформы может настраивать только администратор CKM.');}
    private static function cryptoKey(): string {$seed=(defined('AUTH_KEY')?(string)AUTH_KEY:'').(defined('SECURE_AUTH_KEY')?(string)SECURE_AUTH_KEY:'').(function_exists('wp_salt')?(string)wp_salt('secure_auth'):'').'|ckm-sales-live-sip-platform-v1';return hash('sha256',$seed,true);}
    private static function encrypt(array $data): string {
        if(!function_exists('openssl_encrypt'))throw new \RuntimeException('На сервере недоступно безопасное шифрование.');$plain=wp_json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if(!is_string($plain))throw new \RuntimeException('Не удалось подготовить настройки голосовой инфраструктуры.');$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($plain,'aes-256-gcm',self::cryptoKey(),OPENSSL_RAW_DATA,$iv,$tag,'ckm-sales-live-sip-platform',16);if(!is_string($cipher)||strlen($tag)!==16)throw new \RuntimeException('Не удалось зашифровать настройки голосовой инфраструктуры.');return 'v1:'.base64_encode($iv.$tag.$cipher);
    }
    private static function decrypt(string $stored): array {
        if($stored===''||!str_starts_with($stored,'v1:')||!function_exists('openssl_decrypt'))return [];$raw=base64_decode(substr($stored,3),true);if(!is_string($raw)||strlen($raw)<=28)return [];$plain=openssl_decrypt(substr($raw,28),'aes-256-gcm',self::cryptoKey(),OPENSSL_RAW_DATA,substr($raw,0,12),substr($raw,12,16),'ckm-sales-live-sip-platform');$data=is_string($plain)?json_decode($plain,true):null;return is_array($data)?$data:[];
    }
    private static function rawSettings(): array {$row=get_option(self::OPTION,[]);if(!is_array($row))$row=[];$secret=self::decrypt((string)($row['secret_cipher']??''));return ['api_key'=>(string)($secret['api_key']??''),'webhook_secret'=>(string)($secret['webhook_secret']??''),'sideband_secret'=>(string)($secret['sideband_secret']??''),'project_id'=>(string)($row['project_id']??''),'region'=>(string)($row['region']??'global'),'voice'=>(string)($row['voice']??'marin')];}
    private static function normalizeProject(string $id): string {$id=trim($id);if(!preg_match('/^proj_[A-Za-z0-9_-]{4,190}$/',$id))throw new \InvalidArgumentException('Project ID OpenAI должен начинаться с proj_.');return $id;}
    private static function normalizeApiKey(string $key): string {$key=trim($key);if(strlen($key)<20||strlen($key)>512||!str_starts_with($key,'sk-')||preg_match('/[\r\n\x00]/',$key))throw new \InvalidArgumentException('API key OpenAI выглядит некорректно.');return $key;}
    private static function normalizeWebhookSecret(string $secret): string {$secret=trim($secret);if($secret!==''&&(!str_starts_with($secret,'whsec_')||strlen($secret)<12||strlen($secret)>512||preg_match('/[\r\n\x00]/',$secret)))throw new \InvalidArgumentException('Webhook signing secret должен начинаться с whsec_.');return $secret;}
    private static function normalizeRegion(string $region): string {$region=sanitize_key($region);return $region==='eu'?'eu':'global';}
    private static function normalizeVoice(string $voice): string {$voice=sanitize_key($voice);if($voice===''||strlen($voice)>40)$voice='marin';return $voice;}
    public static function webhookUrl(): string {return rest_url('ckm/v1/sales/live-sip/webhook');}
    public static function sipUri(?string $projectId=null,?string $region=null): string {$s=self::rawSettings();$projectId=$projectId??(string)$s['project_id'];$region=self::normalizeRegion($region??(string)$s['region']);if($projectId==='')return '';return 'sip:'.$projectId.'@'.($region==='eu'?'sip-eu.api.openai.com':'sip.api.openai.com').';transport=tls';}
    public static function sidebandSecretForServer(): string {return (string)self::rawSettings()['sideband_secret'];}
    public static function platformProjectId(): string {return (string)self::rawSettings()['project_id'];}
    public static function platformReady(): bool {$s=self::rawSettings();return (string)$s['api_key']!==''&&(string)$s['project_id']!==''&&(string)$s['webhook_secret']!=='';}
    public static function platformStatus(): array {$s=self::rawSettings();$key=(string)$s['api_key'];return ['configured'=>self::platformReady(),'project_id'=>(string)$s['project_id'],'region'=>(string)$s['region'],'voice'=>(string)$s['voice'],'api_key_set'=>$key!=='','api_key_hint'=>$key!==''?'••••'.substr($key,-4):'','webhook_secret_set'=>(string)$s['webhook_secret']!=='','sideband_secret_set'=>(string)$s['sideband_secret']!=='','sideband'=>class_exists(SalesLiveSidebandService::class)?SalesLiveSidebandService::workerStatus():['configured'=>(string)$s['sideband_secret']!=='','online'=>false],'webhook_url'=>self::webhookUrl(),'sip_uri'=>self::sipUri((string)$s['project_id'],(string)$s['region']),'model'=>self::MODEL];}
    public static function savePlatformSettings(string $apiKey,string $projectId,string $webhookSecret,string $region,string $voice,string $sidebandSecret=''): array {
        self::requireAdmin();$old=self::rawSettings();$apiKey=trim($apiKey)!==''?self::normalizeApiKey($apiKey):(string)$old['api_key'];$webhookSecret=trim($webhookSecret)!==''?self::normalizeWebhookSecret($webhookSecret):(string)$old['webhook_secret'];$sidebandSecret=trim($sidebandSecret)!==''?trim($sidebandSecret):(string)$old['sideband_secret'];if($sidebandSecret!==''&&(strlen($sidebandSecret)<24||strlen($sidebandSecret)>190||preg_match('/[\r\n\x00]/',$sidebandSecret)))throw new \InvalidArgumentException('Sideband worker secret должен содержать не менее 24 символов.');if($apiKey==='')throw new \InvalidArgumentException('Введите API key платформы.');$projectId=self::normalizeProject($projectId);$region=self::normalizeRegion($region);$voice=self::normalizeVoice($voice);update_option(self::OPTION,['project_id'=>$projectId,'region'=>$region,'voice'=>$voice,'secret_cipher'=>self::encrypt(['api_key'=>$apiKey,'webhook_secret'=>$webhookSecret,'sideband_secret'=>$sidebandSecret])],false);return self::platformStatus();
    }
    private function request(string $method,string $path,?array $body=null,int $timeout=20): array {
        $s=self::rawSettings();$key=self::normalizeApiKey((string)$s['api_key']);$headers=['Authorization'=>'Bearer '.$key,'Accept'=>'application/json'];if((string)$s['project_id']!=='')$headers['OpenAI-Project']=(string)$s['project_id'];if($body!==null)$headers['Content-Type']='application/json';
        if($this->transport){$out=($this->transport)($method,$path,$body,$headers);if(!is_array($out))throw new \RuntimeException('Live SIP transport вернул некорректный ответ.');return $out;}
        $args=['method'=>$method,'timeout'=>$timeout,'redirection'=>0,'headers'=>$headers];if($body!==null)$args['body']=wp_json_encode($body,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$resp=wp_remote_request(self::API_BASE.$path,$args);if(is_wp_error($resp))throw new \RuntimeException('OpenAI Live API недоступен: '.$resp->get_error_message());$code=(int)wp_remote_retrieve_response_code($resp);$raw=(string)wp_remote_retrieve_body($resp);$data=$raw!==''?json_decode($raw,true):[];if($code<200||$code>=300){$msg=is_array($data)?self::clean((string)($data['error']['message']??''),500):'';throw new \RuntimeException($msg!==''?'OpenAI Live API: '.$msg:'OpenAI Live API вернул HTTP '.$code.'.');}return is_array($data)?$data:[];
    }
    public function testPlatform(): array {self::requireAdmin();if(!self::platformReady())throw new \RuntimeException('Сначала сохраните API key, Project ID и webhook signing secret.');$this->request('GET','/models/'.self::MODEL,null,15);return ['ok'=>true]+self::platformStatus();}
    private static function e164(string $value): string {$digits=preg_replace('/\D+/','',$value);if(!is_string($digits)||!preg_match('/^[0-9]{7,15}$/',$digits))throw new \InvalidArgumentException('Номер должен быть в международном формате.');return '+'.$digits;}
    private static function sessionConfig(array $script): array {return ['model'=>self::MODEL,'instructions'=>SalesAiSellerService::voicePromptForScript($script),'audio'=>['output'=>['voice'=>(string)self::rawSettings()['voice']]]];}
    private static function rememberCall(array $row): void {$calls=get_option(self::CALLS_OPTION,[]);if(!is_array($calls))$calls=[];array_unshift($calls,$row);$calls=array_slice($calls,0,200);update_option(self::CALLS_OPTION,$calls,false);}
    public function startOutbound(array $script,array $integration,string $destination): array {
        if(!self::platformReady())throw new \RuntimeException('Администратор CKM ещё не настроил голосовую инфраструктуру платформы.');if((string)($integration['provider']??'')!=='sip')throw new \InvalidArgumentException('Телефонное подключение не найдено.');$cred=SalesPartnerIntegrationService::credentialsForRow($integration);if((string)($cred['adapter']??'')!=='direct_sip')throw new \InvalidArgumentException('Для прямого AI-звонка назначьте агенту подключение Direct SIP.');$providerUrl=SalesTelephonyService::normalizeDirectSipUrl((string)($cred['provider_url']??''));$destination=self::e164($destination);$caller=self::e164((string)($cred['caller_id']??''));$username=(string)($cred['username']??'');$password=(string)($cred['password']??'');if($username===''||$password==='')throw new \RuntimeException('В Direct SIP отсутствуют trunk-учётные данные.');
        $body=['session'=>self::sessionConfig($script),'transport'=>['type'=>'sip','destination'=>$destination,'trunk'=>['provider_url'=>$providerUrl,'auth'=>['type'=>'digest','username'=>$username,'password'=>$password],'caller_number'=>$caller]]];$data=$this->request('POST','/live/sessions',$body,25);$sessionId=(string)($data['session']['id']??'');if($sessionId==='')throw new \RuntimeException('Live API не вернул session.id. Повторять запрос автоматически нельзя: исходящий звонок мог уже начаться.');self::rememberCall(['session_id'=>$sessionId,'direction'=>'outbound','integration_id'=>(string)($integration['integration_id']??''),'tenant_id'=>(int)($integration['tenant_id']??0),'script_id'=>(string)($script['id']??''),'destination'=>$destination,'status'=>'initialized','created_at'=>gmdate('c')]);if(class_exists(SalesLiveSidebandService::class))SalesLiveSidebandService::registerCall($sessionId,['owner_user_id'=>(int)($integration['assigned_user_id']??0),'scope'=>(string)($integration['assigned_scope']??'default'),'script_id'=>(string)($script['id']??''),'tenant_id'=>(int)($integration['tenant_id']??0),'integration_id'=>(string)($integration['integration_id']??''),'direction'=>'outbound','lead_contact'=>$destination,'call_status'=>'initialized']);return ['ok'=>true,'session_id'=>$sessionId,'destination'=>$destination];
    }
    private static function header(array $headers,string $name): string {$wanted=str_replace('_','-',strtolower($name));foreach($headers as $k=>$v){$actual=str_replace('_','-',strtolower((string)$k));if($actual===$wanted)return is_array($v)?(string)reset($v):(string)$v;}return '';}
    private static function secretBytes(string $secret): string {$raw=str_starts_with($secret,'whsec_')?substr($secret,6):$secret;$raw=strtr($raw,'-_','+/');$pad=strlen($raw)%4;if($pad)$raw.=str_repeat('=',4-$pad);$decoded=base64_decode($raw,true);return is_string($decoded)&&$decoded!==''?$decoded:$secret;}
    public static function verifyWebhookSignature(string $raw,array $headers,?int $now=null): bool {
        $s=self::rawSettings();$secret=(string)$s['webhook_secret'];if($secret==='')return false;$id=self::header($headers,'webhook-id');$timestamp=self::header($headers,'webhook-timestamp');$signature=self::header($headers,'webhook-signature');if($id===''||!ctype_digit($timestamp)||$signature==='')return false;$now=$now??time();if(abs($now-(int)$timestamp)>self::WEBHOOK_TOLERANCE)return false;$expected=base64_encode(hash_hmac('sha256',$id.'.'.$timestamp.'.'.$raw,self::secretBytes($secret),true));foreach(preg_split('/\s+/',trim($signature))?:[] as $part){if(!str_starts_with($part,'v1,'))continue;$given=substr($part,3);if(hash_equals($expected,$given))return true;}return false;
    }
    private static function extractNumber(array $headers,string $wanted): string {foreach($headers as $h){if(!is_array($h)||strcasecmp((string)($h['name']??''),$wanted)!==0)continue;$v=(string)($h['value']??'');if(preg_match('/(?:sip:|tel:)?\+?([0-9]{7,15})/i',$v,$m))return (string)$m[1];}return '';}
    private function reject(string $sessionId,int $status=480): void {try{$this->request('POST','/live/sessions/'.rawurlencode($sessionId).'/reject',['status_code'=>$status],12);}catch(\Throwable){} }
    public function handleIncomingWebhook(string $raw,array $headers): array {
        if(!self::verifyWebhookSignature($raw,$headers))throw new \InvalidArgumentException('Подпись OpenAI webhook не прошла проверку.');$event=json_decode($raw,true);if(!is_array($event))throw new \InvalidArgumentException('Webhook содержит некорректный JSON.');$type=(string)($event['type']??'');if($type!=='live.transport.incoming')return ['ignored'=>true,'event_type'=>$type];$data=is_array($event['data']??null)?$event['data']:[];if((string)($data['type']??'')!=='sip')return ['ignored'=>true,'event_type'=>$type];$sessionId=self::clean((string)($data['session_id']??''),190);if($sessionId==='')throw new \InvalidArgumentException('Webhook не содержит session_id.');$webhookId=self::header($headers,'webhook-id');$dedupe='ckm_sales_live_sip_wh_'.md5($webhookId);if($webhookId!==''&&get_transient($dedupe))return ['duplicate'=>true,'session_id'=>$sessionId];$sipHeaders=is_array($data['sip_headers']??null)?$data['sip_headers']:[];$did=self::extractNumber($sipHeaders,'To');$caller=self::extractNumber($sipHeaders,'From');$integration=$did!==''?SalesPartnerIntegrationService::assignedSipByInboundNumber($did):null;if(!$integration){$this->reject($sessionId,480);if($webhookId!=='')set_transient($dedupe,1,DAY_IN_SECONDS);return ['accepted'=>false,'rejected'=>true,'reason'=>'no_route','did'=>$did];}$script=SalesScriptService::findForOwner((int)$integration['assigned_user_id'],(string)$integration['assigned_scope'],(string)$integration['assigned_script_id']);if(!$script||empty($script['ai_seller_enabled'])){$this->reject($sessionId,480);if($webhookId!=='')set_transient($dedupe,1,DAY_IN_SECONDS);return ['accepted'=>false,'rejected'=>true,'reason'=>'agent_unavailable','did'=>$did];}$this->request('POST','/live/sessions/'.rawurlencode($sessionId).'/accept',['session'=>array_merge(['type'=>'live'],self::sessionConfig($script))],15);if($webhookId!=='')set_transient($dedupe,1,DAY_IN_SECONDS);self::rememberCall(['session_id'=>$sessionId,'direction'=>'inbound','integration_id'=>(string)$integration['integration_id'],'tenant_id'=>(int)$integration['tenant_id'],'script_id'=>(string)$script['id'],'destination'=>$did,'status'=>'accepted','created_at'=>gmdate('c')]);if(class_exists(SalesLiveSidebandService::class))SalesLiveSidebandService::registerCall($sessionId,['owner_user_id'=>(int)$integration['assigned_user_id'],'scope'=>(string)$integration['assigned_scope'],'script_id'=>(string)$script['id'],'tenant_id'=>(int)$integration['tenant_id'],'integration_id'=>(string)$integration['integration_id'],'direction'=>'inbound','lead_contact'=>$caller!==''?'+'.$caller:'','call_status'=>'accepted']);return ['accepted'=>true,'session_id'=>$sessionId,'did'=>$did,'caller'=>$caller];
    }
    public function refer(string $sessionId,string $targetUri): void {$targetUri=trim($targetUri);if(!preg_match('/^(?:sip:|sips:|tel:).+/i',$targetUri))throw new \InvalidArgumentException('Укажите корректный SIP/TEL адрес для перевода.');$this->request('POST','/live/sessions/'.rawurlencode($sessionId).'/refer',['target_uri'=>$targetUri],12);}
    public function hangup(string $sessionId): void {$this->request('POST','/live/sessions/'.rawurlencode($sessionId).'/hangup',null,12);}
}
