<?php
namespace CKM\EffectiveSales;
if (!defined('ABSPATH')) { exit; }

/**
 * Phone media gateway control plane for the existing CKM Sergey/Cartesia voice.
 * WordPress never handles RTP/audio. A long-lived gateway receives PBX media,
 * sends 8 kHz PCM to Deepgram Nova-3 (ru), asks the existing AI seller for text,
 * then asks the already configured CKM Voice Gateway to synthesize Sergey.
 */
final class SalesPhoneGatewayService {
    private const OPTION='ckm_sales_phone_gateway_v1';
    private const HEARTBEAT='ckm_sales_phone_gateway_heartbeat_v1';
    private const CALLS='ckm_sales_phone_gateway_calls_v1';
    private const MAX_CALLS=300;
    private const ONLINE_TTL=45;
    private const COMMAND_TTL=120;

    private static function clean(string $v,int $max=500): string {$v=trim(wp_strip_all_tags($v));return function_exists('mb_substr')?mb_substr($v,0,$max,'UTF-8'):substr($v,0,$max);}
    private static function requireAdmin(): void {if(!current_user_can('manage_options'))throw new \RuntimeException('Телефонный медиашлюз может настраивать только администратор CKM.');}
    private static function raw(): array {$v=get_option(self::OPTION,[]);return is_array($v)?$v:[];}
    private static function secret(): string {return (string)(self::raw()['secret']??'');}
    private static function assertSecret(string $given): void {$expected=self::secret();if($expected===''||$given===''||!hash_equals($expected,$given))throw new \InvalidArgumentException('Phone gateway не авторизован.');}
    private static function calls(): array {$v=get_option(self::CALLS,[]);return is_array($v)?$v:[];}
    private static function saveCalls(array $v): void {uasort($v,static fn($a,$b): int=>strcmp((string)($b['updated_at']??''),(string)($a['updated_at']??'')));update_option(self::CALLS,array_slice($v,0,self::MAX_CALLS,true),false);}
    private static function digits(string $v,bool $optional=false): string {$d=preg_replace('/\D+/','',$v);if(!is_string($d))$d='';if($d===''&&$optional)return '';if(!preg_match('/^[0-9]{7,15}$/',$d))throw new \InvalidArgumentException('Телефон должен быть в международном формате.');return $d;}
    private static function uuid(string $v): string {$v=strtolower(trim($v));if(!preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/',$v))throw new \InvalidArgumentException('Некорректный UUID телефонного звонка.');return $v;}
    private static function workerMeta(): array {$v=get_option(self::HEARTBEAT,[]);return is_array($v)?$v:[];}
    public static function workerOnline(): bool {$m=self::workerMeta();return (int)($m['at']??0)>=time()-self::ONLINE_TTL;}
    public static function platformStatus(): array {
        $voiceReady=function_exists('ckm_quiz_pro_voice_ready')&&ckm_quiz_pro_voice_ready()&&function_exists('ckm_quiz_pro_ai_voice_provider')&&ckm_quiz_pro_ai_voice_provider()==='gateway';
        $gateway=function_exists('ckm_quiz_pro_voice_gateway_base_url')?ckm_quiz_pro_voice_gateway_base_url():'';
        $m=self::workerMeta();
        return ['configured'=>self::secret()!=='','worker_online'=>self::workerOnline(),'worker_last_seen'=>(int)($m['at']??0)>0?gmdate('c',(int)$m['at']):'','worker_meta'=>$m,'sergey_ready'=>$voiceReady,'voice_gateway_url'=>$gateway,'voice_label'=>'Сергей · Cartesia','stt_label'=>'Deepgram Nova-3 · ru','heartbeat_url'=>rest_url('ckm/v1/sales/phone-gateway/heartbeat'),'open_url'=>rest_url('ckm/v1/sales/phone-gateway/open'),'turn_url'=>rest_url('ckm/v1/sales/phone-gateway/turn'),'speak_url'=>rest_url('ckm/v1/sales/phone-gateway/speak')];
    }
    public static function savePlatformSettings(string $secret): array {self::requireAdmin();$old=self::secret();$secret=trim($secret);if($secret==='')$secret=$old;if(strlen($secret)<24||strlen($secret)>190||preg_match('/[\r\n\x00]/',$secret))throw new \InvalidArgumentException('Phone gateway secret должен содержать 24–190 символов.');update_option(self::OPTION,['secret'=>$secret,'updated_at'=>gmdate('c')],false);return self::platformStatus();}
    public static function testPlatform(): array {self::requireAdmin();$s=self::platformStatus();if(empty($s['configured']))throw new \RuntimeException('Сначала сохраните Phone gateway secret.');if(empty($s['sergey_ready']))throw new \RuntimeException('Сергей ещё не включён в основном CKM Voice Gateway.');$health=function_exists('ckm_quiz_pro_voice_gateway_health')?ckm_quiz_pro_voice_gateway_health():['ok'=>false];if(empty($health['ok'])||empty($health['tts']['configured']))throw new \RuntimeException('CKM Voice Gateway не подтвердил готовность Cartesia/Сергея.');return ['ok'=>true,'health'=>$health]+$s;}
    public static function heartbeat(string $secret,array $meta=[]): array {self::assertSecret($secret);$safe=['at'=>time(),'service'=>self::clean((string)($meta['service']??'ckm-phone-media-gateway'),80),'version'=>self::clean((string)($meta['version']??''),80),'deepgram_ready'=>!empty($meta['deepgram_ready']),'audiosocket_ready'=>!empty($meta['audiosocket_ready']),'active_calls'=>max(0,(int)($meta['active_calls']??0))];update_option(self::HEARTBEAT,$safe,false);return self::platformStatus();}
    private static function scriptForRow(array $row): array {$uid=(int)($row['owner_user_id']??0);$scope=(string)($row['assigned_scope']??'default');$scriptId=(string)($row['assigned_script_id']??'');$script=SalesScriptService::findForOwner($uid,$scope,$scriptId);if(!$script||empty($script['ai_seller_enabled'])||(string)($script['ai_seller_token']??'')==='')throw new \RuntimeException('Для этого номера не найден активный ИИ-продавец.');return $script;}
    public static function open(string $secret,string $callUuid,string $did,string $caller): array {
        self::assertSecret($secret);$callUuid=self::uuid($callUuid);$did=self::digits($did);$caller=self::digits($caller,true);$integration=SalesPartnerIntegrationService::assignedSipByInboundNumber($did);if(!$integration)throw new \InvalidArgumentException('Этот DID не назначен ИИ-продавцу.');$script=self::scriptForRow($integration);$calls=self::calls();$now=gmdate('c');$calls[$callUuid]=['call_uuid'=>$callUuid,'owner_user_id'=>(int)$integration['assigned_user_id'],'scope'=>(string)$integration['assigned_scope'],'script_id'=>(string)$integration['assigned_script_id'],'integration_id'=>(string)$integration['integration_id'],'did'=>$did,'caller'=>$caller,'direction'=>'inbound','status'=>'active','call_status'=>'connected','dialog_id'=>(string)($calls[$callUuid]['dialog_id']??''),'commands'=>[],'created_at'=>(string)($calls[$callUuid]['created_at']??$now),'updated_at'=>$now];self::saveCalls($calls);return ['call_uuid'=>$callUuid,'script_id'=>(string)$integration['assigned_script_id'],'integration_id'=>(string)$integration['integration_id'],'voice'=>'Сергей · Cartesia','stt'=>'Deepgram Nova-3 · ru','lead_contact'=>$caller!==''?'+'.$caller:'','agent_name'=>(string)($script['ai_seller_name']??'ИИ-продавец')];
    }
    private static function row(string $uuid): array {$uuid=self::uuid($uuid);$calls=self::calls();$row=$calls[$uuid]??null;if(!is_array($row))throw new \InvalidArgumentException('Телефонный звонок не зарегистрирован.');return $row;}
    private static function seller(array $row): array {$integration=SalesPartnerIntegrationService::integrationForSession((string)$row['integration_id'],(int)$row['owner_user_id'],(string)$row['scope'],(string)$row['script_id'],'sip');if(!$integration)throw new \RuntimeException('Телефонное подключение больше не назначено этому агенту.');$script=SalesScriptService::findForOwner((int)$row['owner_user_id'],(string)$row['scope'],(string)$row['script_id']);if(!$script||empty($script['ai_seller_enabled']))throw new \RuntimeException('ИИ-продавец выключен.');$token=(string)($script['ai_seller_token']??'');if($token==='')throw new \RuntimeException('У ИИ-продавца нет активного токена.');return [$script,$token,$integration];}
    public static function turn(string $secret,string $callUuid,string $text): array {
        self::assertSecret($secret);$callUuid=self::uuid($callUuid);$row=self::row($callUuid);[$script,$token,$integration]=self::seller($row);$lead=(string)($row['caller']??'');$svc=new SalesAiSellerService();$result=$svc->externalMessage($token,'phone',$callUuid,$lead!==''?'Телефон +'.$lead:'Телефонный клиент',$lead!==''?'+'.$lead:'',$text,(string)$row['integration_id']);$dialog=(string)($result['session_id']??'');$calls=self::calls();if(isset($calls[$callUuid])){$calls[$callUuid]['dialog_id']=$dialog;$calls[$callUuid]['updated_at']=gmdate('c');$calls[$callUuid]['call_status']='active';self::saveCalls($calls);}if($dialog!=='')SalesAiSellerWorkspaceService::recordLiveCallState(['id'=>$dialog,'owner_user_id'=>(int)$row['owner_user_id']],'active',false,[]);$ticket=$dialog!==''?$svc->voiceTicket($token,$dialog):[];return $result+['call_uuid'=>$callUuid,'voice_ticket'=>$ticket];
    }
    public static function speak(string $secret,string $callUuid,int $turnIndex): array {self::assertSecret($secret);$row=self::row($callUuid);[, $token]=self::seller($row);$dialog=(string)($row['dialog_id']??'');if($dialog==='')throw new \RuntimeException('У звонка ещё нет диалога ИИ-продавца.');return (new SalesAiSellerService())->speak($token,$dialog,$turnIndex);}
    public static function event(string $secret,string $callUuid,string $status,string $detail=''): array {
        self::assertSecret($secret);$callUuid=self::uuid($callUuid);$calls=self::calls();if(!isset($calls[$callUuid])||!is_array($calls[$callUuid]))throw new \InvalidArgumentException('Телефонный звонок не зарегистрирован.');$allowed=['connected','active','completed','hangup','failed','transfer_requested','transfer_failed','transferred'];$status=sanitize_key($status);if(!in_array($status,$allowed,true))throw new \InvalidArgumentException('Неизвестное состояние звонка.');$calls[$callUuid]['call_status']=$status;$calls[$callUuid]['updated_at']=gmdate('c');if(in_array($status,['completed','hangup','failed','transferred'],true))$calls[$callUuid]['status']='closed';if($detail!=='')$calls[$callUuid]['detail']=self::clean($detail,800);$dialog=(string)($calls[$callUuid]['dialog_id']??'');$uid=(int)$calls[$callUuid]['owner_user_id'];self::saveCalls($calls);if($dialog!=='')SalesAiSellerWorkspaceService::recordLiveCallState(['id'=>$dialog,'owner_user_id'=>$uid],$status,in_array($status,['completed','hangup','failed','transferred'],true),[]);return ['accepted'=>true,'call_status'=>$status];
    }
    public static function commands(string $secret,string $callUuid): array {self::assertSecret($secret);$callUuid=self::uuid($callUuid);$calls=self::calls();if(!isset($calls[$callUuid])||!is_array($calls[$callUuid]))return [];$cmds=is_array($calls[$callUuid]['commands']??null)?array_values($calls[$callUuid]['commands']):[];$now=time();$out=[];foreach($cmds as $c){if(!is_array($c)||!empty($c['claimed'])||((int)($c['at']??0)<$now-self::COMMAND_TTL))continue;$c['claimed']=true;$out[]=$c;}$calls[$callUuid]['commands']=[];$calls[$callUuid]['updated_at']=gmdate('c');self::saveCalls($calls);return $out;}
    private static function ownedByDialog(string $scriptId,string $dialogId): array {$uid=get_current_user_id();if($uid<1)throw new \RuntimeException('Требуется вход.');$scope=SalesScriptService::currentScopeKey();foreach(self::calls() as $row)if(is_array($row)&&(string)($row['dialog_id']??'')===$dialogId&&(string)($row['script_id']??'')===$scriptId&&(int)($row['owner_user_id']??0)===$uid&&(string)($row['scope']??'')===$scope)return $row;throw new \InvalidArgumentException('Телефонный диалог не найден.');}
    public static function dialogStatus(string $scriptId,string $dialogId): array {try{$row=self::ownedByDialog($scriptId,$dialogId);}catch(\Throwable){return ['phone'=>false];}$integration=SalesPartnerIntegrationService::integrationForSession((string)$row['integration_id'],(int)$row['owner_user_id'],(string)$row['scope'],(string)$row['script_id'],'sip');$target='';if($integration){$cred=SalesPartnerIntegrationService::credentialsForRow($integration);$target=(string)($cred['handoff_target_uri']??'');}return ['phone'=>true,'call_uuid'=>(string)$row['call_uuid'],'call_status'=>(string)($row['call_status']??'active'),'active'=>(string)($row['status']??'')!=='closed','handoff_target'=>$target,'can_transfer'=>$target!==''&&self::workerOnline()];}
    private static function queueCommand(array $row,array $cmd): void {$uuid=(string)$row['call_uuid'];$calls=self::calls();if(!isset($calls[$uuid])||!is_array($calls[$uuid]))throw new \InvalidArgumentException('Телефонный звонок не найден.');$cmd['id']=wp_generate_uuid4();$cmd['at']=time();$list=is_array($calls[$uuid]['commands']??null)?$calls[$uuid]['commands']:[];$list[]=$cmd;$calls[$uuid]['commands']=array_slice($list,-10);$calls[$uuid]['updated_at']=gmdate('c');self::saveCalls($calls);}
    public static function hangupCurrentUser(string $scriptId,string $dialogId): array {$row=self::ownedByDialog($scriptId,$dialogId);self::queueCommand($row,['type'=>'hangup']);SalesAiSellerWorkspaceService::recordLiveCallState(['id'=>$dialogId,'owner_user_id'=>(int)$row['owner_user_id']],'hangup_requested',false,[]);return ['ok'=>true,'queued'=>true];}
    public static function transferCurrentUser(string $scriptId,string $dialogId): array {$row=self::ownedByDialog($scriptId,$dialogId);$integration=SalesPartnerIntegrationService::integrationForSession((string)$row['integration_id'],(int)$row['owner_user_id'],(string)$row['scope'],(string)$row['script_id'],'sip');if(!$integration)throw new \RuntimeException('Телефонное подключение не найдено.');$cred=SalesPartnerIntegrationService::credentialsForRow($integration);$target=SalesTelephonyService::normalizeHandoffTarget((string)($cred['handoff_target_uri']??''),false);self::queueCommand($row,['type'=>'transfer','target_uri'=>$target]);SalesAiSellerWorkspaceService::recordLiveCallState(['id'=>$dialogId,'owner_user_id'=>(int)$row['owner_user_id']],'transfer_requested',false,[]);return ['ok'=>true,'queued'=>true,'target_uri'=>$target];}
}
